from .animal import Animal
from .llama import Llama
from .pig import Pig
from .donkey import Donkey
from .rabbit import Rabbit
from .goat import Goat
from .turtle import Turtle
from .duck import Duck
from .otter import Otter
from .catfish import Catfish
from .stingray import Stingray
from .skink import Skink
from .gecko import Gecko
from .iguana import Iguana
from .boa import Boa
from .cornsnake import Cornsnake
